language: node_js
node_js:
  - "stable"
env:
  global: 
    - REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY
    - REACT_APP_FIREBASE_APP_ID=$FIREBASE_APP_ID
    - REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
    - REACT_APP_FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
    - REACT_APP_FIREBASE_MESSAGING_ID=$FIREBASE_MESSAGING_ID
    - REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
    - REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master